/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.InfoSecOfficerRole;
import Business.Enterprise.Enterprise;
import Business.Organization.DataSecurityOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.InformationSecurityOraganization;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.Utils.SendMails;
import Business.WorkQueue.DataAnalysisWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.plaf.basic.DefaultMenuLayout;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.time.Second;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.layout.FormatLayout;
import org.jfree.ui.TextAnchor;
import userinterface.ReceptionistRole.RequestBookingAppointmentJPanel;
@SuppressWarnings("deprecation")
/**
 *
 * @author anike
 */
public class InfoSecOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoSecOfficerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private InformationSecurityOraganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private volatile boolean running;
      private static TimeSeries ts = new TimeSeries("data", Second.class);
    private Random randGen = new Random();
    public InfoSecOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InformationSecurityOraganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        running = true;
         
    }

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnViewAuthenticationLogs = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("View Data Transmission");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnViewAuthenticationLogs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewAuthenticationLogs.setForeground(new java.awt.Color(0, 204, 255));
        btnViewAuthenticationLogs.setText("View Authentcation Logs");
        btnViewAuthenticationLogs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewAuthenticationLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAuthenticationLogsActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Send Alert Mail");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 255));
        jButton3.setText("Request Analysis Team");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("My Work Area");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/utils/user_login_man_profile_account-128.png"))); // NOI18N

        jLabel9.setText("You are currently logged in.");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 255));
        jButton4.setText("Set Employee Status");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel5)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewAuthenticationLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewAuthenticationLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void raiseThreatRequest(){
        
        String message = " Message-Critical check" ;
     
        DataAnalysisWorkRequest request = new DataAnalysisWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DataSecurityOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Threat request raised");
        
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        running = true;
        new Thread(){
            public void run(){
                while(running){
                    int num = 100 + randGen.nextInt(100000);
                    ts.addOrUpdate(new Second(), num);
                    if ((num >85000) && (num <95000)){
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane p = new JOptionPane();
                        p.setMessage("Possibility of Threat...Please raise analysis request");
                        JDialog d = p.createDialog(p, "ALERT!!!");                        
                        d.setLayout(new FlowLayout());                       
                        d.setSize(335,140);
                        d.getContentPane().setForeground(Color.black);
                        d.getContentPane().setBackground(Color.red);
                        d.setModalityType(Dialog.ModalityType.MODELESS);
                        d.setVisible(true);
                    }else if(num > 95000){
                        raiseThreatRequest();
                    }
                    
                    try {
                        Thread.sleep(500);
                        Thread.yield();    
                        
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                }
            }
        }.start();

        TimeSeriesCollection dataset = new TimeSeriesCollection(ts);
        JFreeChart chart = ChartFactory.createTimeSeriesChart(
            "Data Transmission",
            "Time",
            "Data Size(kb)",
            dataset,
            true,
            true,
            false
        );
        final XYPlot plot = chart.getXYPlot();
        org.jfree.chart.axis.ValueAxis axis = plot.getDomainAxis();
        axis.setAutoRange(true);
        axis.setFixedAutoRange(60000.0);
        ValueMarker mark = new ValueMarker(80000);
        mark.setLabel("Threshold Value");
        mark.setPaint(Color.BLACK);
        mark.setLabelTextAnchor(TextAnchor.TOP_RIGHT);
        plot.addRangeMarker(mark);

        JFrame frame = new JFrame("Data Transmission Graph");
         frame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) { 
               running = false;
      }
});
        ChartPanel label = new ChartPanel(chart);
        frame.getContentPane().add(label);
        frame.pack();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewAuthenticationLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAuthenticationLogsActionPerformed

        String workingdirectory = System.getProperty("user.dir");
        workingdirectory += "\\log\\";
        workingdirectory += "log.txt";
        Runtime rs = Runtime.getRuntime();
        ProcessBuilder pb = new ProcessBuilder("Notepad.exe", workingdirectory);

        File f = new File(workingdirectory);
        if (f.exists() && !f.isDirectory()) {
            try {
                pb.start();
            } catch (IOException e) {
                System.out.println(e);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Log File Absent");
        }

    }//GEN-LAST:event_btnViewAuthenticationLogsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = null;
            
            for (UserAccount acc : enterprise.getUserAccountDirectory().getUserAccountList()) {
         
                if (acc.getRole().toString().matches(Role.RoleType.ConfigurationHospitalManager.toString())||
                     acc.getRole().toString().matches(Role.RoleType.ConfigurationPharmaManager.toString())   ) {
                    id = acc.getEmployee().getEmailid();
                }
            }
            SendEmail(id);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        RequestThreatAnalysisJPanel requestAnalysis = new RequestThreatAnalysisJPanel(userProcessContainer, userAccount,enterprise);
        userProcessContainer.add("requestAnalysis", requestAnalysis);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        ViewDirectoryJPanel viewDirectoryJPanel = new ViewDirectoryJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ViewDirectoryJPanel", viewDirectoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

     public void SendEmail(String toMail) {

        String mailTo = new String(toMail);
        String mailSubject = new String("Alert Reported!!Possibility of Threat");
        String mailText = new String("Alert Reported");
        SendMails newGmailClient = new SendMails();
        newGmailClient.setAccountDetails();
        String mailFrom = newGmailClient.getMailId();
        newGmailClient.sendGmail(mailFrom, mailTo, mailSubject, mailText);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewAuthenticationLogs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
